# Generated by Django 5.0.3 on 2024-03-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
