# Generated by Django 5.0.3 on 2024-03-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salePrice',
            field=models.FloatField(default=60),
            preserve_default=False,
        ),
    ]
