# Generated by Django 5.0.3 on 2024-03-14 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_saleprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
