# Generated by Django 5.0.3 on 2024-03-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='images/users/default.jpeg', upload_to='images/users/'),
        ),
    ]
